//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION
    {
        public OPCION()
        {
            this.RESPUESTA = new HashSet<RESPUESTA>();
        }
    
        public int Numero { get; set; }
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual PREGUNTA PREGUNTA { get; set; }
        public virtual ICollection<RESPUESTA> RESPUESTA { get; set; }
    }
}
