//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPUESTA
    {
        public string Email { get; set; }
        public int Numero { get; set; }
        public int Id { get; set; }
    
        public virtual OPCION OPCION { get; set; }
        public virtual PREGUNTA PREGUNTA { get; set; }
        public virtual USER USER { get; set; }
    }
}
