//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Token { get; set; }
        public string Vip { get; set; }
    
        public virtual RESPUESTA RESPUESTA { get; set; }
    }
}
